# Generated by Django 3.2.3 on 2021-06-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='verification_status',
            field=models.CharField(choices=[('VERIFIED', 'Verified'), ('UNVERIFIED', 'Unverified'), ('UNDER_REVIEW', 'Under Review'), ('REJECTED', 'Rejected')], default='UNVERIFIED', max_length=20),
        ),
    ]
