# Generated by Django 3.2.3 on 2021-05-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='tag',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
