# Generated by Django 3.2.4 on 2021-06-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_alter_bot_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='server_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
