# Generated by Django 3.2.3 on 2021-05-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_alter_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
