# Generated by Django 3.2.4 on 2021-07-27 16:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_alter_bot_server_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('invite_link', models.URLField()),
                ('votes', models.IntegerField(default=0)),
                ('verification_status', models.CharField(choices=[('VERIFIED', 'Verified'), ('UNVERIFIED', 'Unverified'), ('UNDER_REVIEW', 'Under Review'), ('REJECTED', 'Rejected')], default='UNVERIFIED', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField()),
                ('member_count', models.IntegerField(default=0, null=True)),
                ('members_online', models.IntegerField(default=0, null=True)),
                ('icon', models.CharField(max_length=100, null=True)),
                ('short_desc', models.CharField(max_length=120, null=True)),
                ('banner_url', models.URLField(default='https://i.postimg.cc/15TN17rQ/xirprofilback.jpg')),
                ('admins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_servers', to='main_site.member')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='main_site.member')),
            ],
        ),
        migrations.CreateModel(
            name='ServerTag',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=25)),
            ],
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='BotTag',
        ),
        migrations.RenameModel(
            old_name='Vote',
            new_name='BotVote',
        ),
        migrations.AlterField(
            model_name='botmeta',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_site.member'),
        ),
        migrations.CreateModel(
            name='ServerVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField(null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_servers', to='main_site.member')),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_votes', to='main_site.server')),
            ],
        ),
        migrations.CreateModel(
            name='ServerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('creation_date', models.DateTimeField()),
                ('reviewed', models.BooleanField(default=False)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_servers', to='main_site.member')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to='main_site.member')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='main_site.server')),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='bots', to='main_site.ServerTag'),
        ),
    ]
