# Generated by Django 3.2.4 on 2021-07-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_auto_20210727_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='long_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
