# Generated by Django 3.2.3 on 2021-05-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_alter_bot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='server_count',
            field=models.IntegerField(default=0),
        ),
    ]
