# Generated by Django 3.2.3 on 2021-05-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_bot_server_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='avatar_url',
            field=models.URLField(default='https://cdn.discordapp.com/embed/avatars/4.png'),
        ),
    ]
