# Generated by Django 3.2.4 on 2021-07-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_server_long_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermeta',
            name='access_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='membermeta',
            name='access_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membermeta',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='is_nsfw',
            field=models.BooleanField(default=False),
        ),
    ]
