# Generated by Django 3.2.4 on 2021-07-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_auto_20210727_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermeta',
            name='admin_servers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
