# Generated by Django 3.2.3 on 2021-05-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_bot_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='short_desc',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='botmeta',
            name='long_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
