# Generated by Django 3.2.4 on 2021-07-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0007_membermeta_admin_servers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='attached_servers', to='main_site.ServerTag'),
        ),
    ]
