# Generated by Django 3.2.4 on 2021-07-28 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0008_alter_server_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='admins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_servers', to='main_site.member'),
        ),
    ]
