# Generated by Django 3.2.4 on 2021-07-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0009_alter_server_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
