# Generated by Django 3.2.3 on 2021-05-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0010_auto_20210528_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botmeta',
            old_name='server_count',
            new_name='shard_count',
        ),
        migrations.AlterField(
            model_name='bot',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='bots', to='main_site.Tag'),
        ),
    ]
