# Generated by Django 3.2.4 on 2021-07-30 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0010_server_banned'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_reason', models.TextField(blank=True, null=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_site.member')),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='main_site.server')),
            ],
        ),
    ]
