# Generated by Django 3.2.3 on 2021-05-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0011_auto_20210528_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmeta',
            name='support_server',
            field=models.URLField(blank=True, null=True),
        ),
    ]
