# Generated by Django 3.2.4 on 2021-07-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0011_servermeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='long_desc',
        ),
        migrations.RemoveField(
            model_name='server',
            name='member_count',
        ),
        migrations.AddField(
            model_name='servermeta',
            name='long_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servermeta',
            name='member_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
