# Generated by Django 3.2.3 on 2021-05-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0013_member_dm_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='bot',
            name='avatar',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
