# Generated by Django 3.2.4 on 2021-07-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0013_auto_20210731_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='admins',
        ),
        migrations.AddField(
            model_name='server',
            name='admins',
            field=models.ManyToManyField(related_name='admin_servers', to='main_site.Member'),
        ),
    ]
