# Generated by Django 3.2.4 on 2021-07-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0014_auto_20210731_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermeta',
            name='rejection_count',
            field=models.IntegerField(default=0),
        ),
    ]
