# Generated by Django 3.2.4 on 2021-07-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0015_servermeta_rejection_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermeta',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
