# Generated by Django 3.2.3 on 2021-05-30 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0015_membermeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermeta',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='main_site.member'),
        ),
    ]
