# Generated by Django 3.2.4 on 2021-08-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0016_servermeta_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmeta',
            name='total_invites',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
