# Generated by Django 3.2.3 on 2021-05-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0016_alter_membermeta_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmeta',
            name='donate',
            field=models.URLField(blank=True, null=True),
        ),
    ]
