# Generated by Django 3.2.3 on 2021-05-31 06:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0017_botmeta_donate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='main_site.member')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_bots', to='main_site.member')),
            ],
        ),
    ]
