# Generated by Django 3.2.4 on 2021-08-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0017_botmeta_total_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermeta',
            name='total_invites',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
