# Generated by Django 3.2.3 on 2021-05-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0018_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='creation_time',
            field=models.DateTimeField(null=True),
        ),
    ]
