# Generated by Django 3.2.4 on 2021-08-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0018_servermeta_total_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='admins',
            field=models.ManyToManyField(related_name='admin_bots', to='main_site.Member'),
        ),
    ]
