# Generated by Django 3.2.4 on 2021-08-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0020_auto_20210826_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='uptime',
        ),
    ]
