# Generated by Django 3.2.3 on 2021-05-31 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0020_auto_20210531_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_votes', to='main_site.bot'),
        ),
    ]
