# Generated by Django 3.2.4 on 2021-09-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0021_remove_bot_uptime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='short_desc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
