# Generated by Django 3.2.4 on 2021-09-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0022_alter_bot_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='short_desc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
