# Generated by Django 3.2.4 on 2021-09-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0023_alter_server_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='invite_link',
            field=models.URLField(max_length=350),
        ),
    ]
